basePath: /v1
definitions:
  Plan:
    properties:
      days:
        description: The days in the plan
        items:
          $ref: '#/definitions/models.Day'
        type: array
      id:
        description: The unique identifier for the plan
        type: integer
    type: object
  models.Day:
    properties:
      day:
        description: The date of the reading day
        type: string
      id:
        description: The unique identifier for the day
        type: integer
      readings:
        description: The readings for the day
        items:
          $ref: '#/definitions/models.Reading'
        type: array
    type: object
  models.Reading:
    properties:
      book:
        description: The book reference
        type: string
      chapter:
        description: The chapter number
        type: integer
      id:
        description: The unique identifier for the reading
        type: integer
      range:
        description: The verse range
        items:
          type: integer
        type: array
    type: object
host: localhost:8000
info:
  contact:
    email: info@mskelton.dev
    name: Mark Skelton
    url: https://mskelton.dev
  description: Bible reading plans
  license:
    name: ISC
    url: https://opensource.org/licenses/ISC
  title: Versly
  version: '1.0'
paths:
  /plans:
    get:
      consumes:
        - application/json
      description: Get a list of plans, with a preview of the first 5 days of readings
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            items:
              $ref: '#/definitions/Plan'
            type: array
      summary: List plans
swagger: '2.0'
