name: Build
on:
  push:
    paths:
      - '.github/**'
      - 'web/**'
defaults:
  run:
    working-directory: web
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: web
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn fmt:check

  ts:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: web
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn ts

  test:
    name: Test
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: web
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn playwright install chromium --with-deps
      - run: yarn db:seed
      - run: yarn test
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results
          path: test-results

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: [lint, ts]
    # needs: [lint, ts, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: web
      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: |
          flyctl deploy --remote-only \
            --build-arg "NEXT_PUBLIC_GA_ID=${{ vars.NEXT_PUBLIC_GA_ID }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
