name: Build
on:
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: yarn install --immutable
      - run: yarn workspace web lint
      - run: yarn format:check

  ts:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: yarn install --immutable
      - run: yarn workspace web ts

  test:
    name: Test
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: yarn install --immutable
      - run: yarn workspace web playwright install chromium --with-deps
      - run: yarn workspace web db:seed
      - run: yarn workspace web test
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results
          path: web/test-results

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: [lint, ts]
    # needs: [lint, ts, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        working-directory: web
        run: |
          flyctl deploy --remote-only \
            --build-arg "NEXT_PUBLIC_GA_ID=${{ vars.NEXT_PUBLIC_GA_ID }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
